
create table if not exists authority (
    id bigint generated by default as identity unique not null,
    name varchar not null unique
);

create table if not exists identity (
    id bigint generated by default as identity unique not null ,
    username varchar not null unique ,
    password varchar not null ,
    email varchar not null unique ,
    phone varchar not null unique ,
    registered_at timestamp not null ,
    enabled boolean not null ,
    authority_id bigint references authority(id) on delete set null on update cascade
);


/* Database Populations */


insert into authority(name) values ('ADMIN');
insert into authority(name) values ('USER');

insert into identity(username, password, email, phone, registered_at, enabled, authority_id)
values ('admin','$2a$10$KrTGHnyrCFcBfNtT/Ugr..L1JZyYKPhUwBxR457ZnZbdTcYjAMjeO',
        'admin@gmail.com','9039035465','2024-10-15',true,1);

insert into identity(username, password, email, phone, registered_at, enabled, authority_id)
values ('user','$2a$10$jS1grVIkmZsTqjYzoZfgyeuQ4nBxaU4zaWZRwDJD2b9oagV//wnni',
        'user@gmail.com','9139037834','2025-11-25',true,2);