
services:

  postgres:
    image: postgres:latest
    container_name: excursion_service_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: excursion_service
      PGDATA: /var/lib/data/postgresql