
services:

  postgres:
    image: postgres:latest
    container_name: excursion_backend_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: excursion_backend
      PGDATA: /var/lib/data/postgresql