
server:
  port: 9020
spring:
  application:
    name: hotel_backend
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/hotel_backend
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 10000MB