
server:
  port: 9010
spring:
  application:
    name: excursion-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/excursion_service
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 50
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        highlight_sql: true