
services:

  postgres:
    image: postgres:latest
    container_name: flight_backend_postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flight_backend
      PGDATA: /var/lib/data/postgresql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: flight_backend_zookeeper
    ports:
      - "2181:2181"
    depends_on:
      - postgres
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: flight_backend_kafka
    depends_on:
      - postgres
      - zookeeper
    ports:
      - "9092:9092"
    restart: unless-stopped
    environment:
      KAFKA_ZOOKEEPER_CONNECT: flight_backend_zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  flight-backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9000"
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - zookeeper
      - kafka
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flight_backend