
create table if not exists image (
    id bigint generated by default as identity unique not null ,
    name varchar not null ,
    content_type varchar not null ,
    size bigint not null ,
    format varchar not null ,
    data bytea not null
);

create table if not exists authority (
    id bigint generated by default as identity unique not null ,
    name varchar not null unique
);

create table if not exists identity (
    id bigint generated by default as identity unique not null ,
    username varchar not null unique ,
    password varchar not null ,
    email varchar not null unique ,
    phone varchar not null unique ,
    registered_at timestamp not null ,
    enabled boolean not null ,
    authority_id bigint references authority(id) on delete set null on update cascade
);

/* POPULATIONS */

insert into authority(name) values ('ADMIN');
insert into authority(name) values ('EMPLOYEE');
insert into authority(name) values ('CLIENT');

insert into identity(username, password, email, phone, registered_at, enabled, authority_id)
values ('admin', 'admin', 'admin@gmail.com', '9039034567', '2025-03-05 14:00', true, 1);

insert into identity(username, password, email, phone, registered_at, enabled, authority_id)
values ('employee', 'employee', 'employee@gmail.com', '9139138901', '2025-03-05 14:00', true, 2);

insert into identity(username, password, email, phone, registered_at, enabled, authority_id)
values ('client', 'client', 'client@gmail.com', '9529521234', '2025-03-05 14:00', true, 3);