
create table if not exists image (
    id bigint generated by default as identity unique not null ,
    name varchar not null ,
    content_type varchar not null ,
    size bigint not null ,
    format varchar not null ,
    data bytea not null
);

create table if not exists authority (
    id bigint generated by default as identity unique not null ,
    name varchar not null unique
);

create table if not exists identity (
    id bigint generated by default as identity unique not null ,
    username varchar not null unique ,
    password varchar not null ,
    email varchar not null unique ,
    phone varchar not null unique ,
    registered_at timestamp not null ,
    enabled boolean not null ,
    authority_id bigint references authority(id) on delete set null on update cascade ,
    image_id bigint references image(id) on delete set null on update cascade
);

/* POPULATIONS */

insert into authority(name) values ('ADMIN');
insert into authority(name) values ('EMPLOYEE');
insert into authority(name) values ('CLIENT');

insert into identity(username, password, email, phone, registered_at, enabled, authority_id, image_id)
values ('admin', '$2a$10$JYue8cgXAyLYN2BMJcbyaObGtAe//WbjMKzheVHoImcL3Nz8xq/Ie', 'admin@gmail.com', '(903)-903-4567',
        '2025-03-05 14:00', true, 1, null);

insert into identity(username, password, email, phone, registered_at, enabled, authority_id, image_id)
values ('employee', '$2a$10$QsHJnLexr/b7UkClaQtjJuvzNBAjeIfzX4ZcKVTtmUFxlBc8G9GRy', 'employee@gmail.com', '(913)-913-8901',
        '2025-03-05 14:00', true, 2, null);

insert into identity(username, password, email, phone, registered_at, enabled, authority_id, image_id)
values ('client', '$2a$10$pC9z0BS.nkrrjW8lOeyAhelaQqhSmSO0QBc4JZfnzv.JFTzs322ZO', 'client@gmail.com', '(952)-952-1234',
        '2025-03-05 14:00', true, 3, null);