

create table if not exists image (
    id bigint generated by default as identity unique not null ,
    name varchar not null ,
    content_type varchar not null ,
    size bigint not null ,
    format varchar not null ,
    data bytea not null
);

create table if not exists authority (
    id bigint generated by default as identity unique not null,
    name varchar not null unique
);

create table if not exists identity (
    id bigint generated by default as identity unique not null ,
    authority_id bigint references authority(id) on delete set null on update cascade ,
    username varchar not null unique ,
    password varchar not null ,
    email varchar not null unique ,
    phone varchar not null unique ,
    registered_at timestamp not null ,
    enabled boolean not null ,
    image_id bigint unique references image(id) on delete set null on update cascade
);

create table if not exists require (
    id bigint generated by default as identity unique not null ,
    name varchar not null ,
    surname varchar not null ,
    patronymic varchar not null ,
    passport varchar not null ,
    closed boolean not null ,
    admin_id bigint references identity(id) on delete set null on update cascade ,
    user_id bigint references identity(id) on delete set null on update cascade
);

create table if not exists require_answer (
    id bigint generated by default as identity unique not null ,
    allowed boolean not null ,
    explanation varchar not null ,
    require_id bigint references require(id) on DELETE set null on update cascade
);

create table if not exists require_answer_token (
    id bigint generated by default as identity unique not null ,
    value uuid not null unique ,
    require_answer_id bigint references require_answer(id) on delete cascade on update cascade
);

create table if not exists restore_token (
    id bigint generated by default as identity unique not null ,
    value uuid not null unique ,
    identity_id bigint unique references identity(id) on delete cascade on update cascade
);

create table if not exists country (
    id bigint generated by default as identity unique not null ,
    name varchar not null unique
);

create table if not exists city (
    id bigint generated by default as identity unique not null ,
    name varchar not null unique ,
    country_id bigint references country(id) on delete cascade on update cascade
);

create table if not exists address (
    id bigint generated by default as identity unique not null ,
    city_id bigint references city(id) on delete set null on update cascade,
    street varchar not null ,
    house varchar not null ,
    apartment varchar
);

create table if not exists airport (
    id bigint generated by default as identity unique not null ,
    name varchar not null unique ,
    address_id bigint references address(id) on delete set null on update cascade ,
    opened boolean not null
);

create table if not exists filial (
    id bigint generated by default as identity unique not null ,
    name varchar not null unique ,
    address_id bigint references address(id) on delete set null on update cascade ,
    opens_at time not null ,
    closes_at time not null ,
    opened boolean not null
);

create table if not exists department (
    id bigint generated by default as identity unique not null ,
    name varchar not null unique ,
    description text not null
);

create table if not exists filial_department (
    id bigint generated by default as identity unique not null ,
    filial_id bigint references filial(id) on delete cascade on update cascade ,
    department_id bigint references department(id) on delete cascade on update cascade
);

create table if not exists position (
    id bigint generated by default as identity unique not null ,
    name varchar not null unique ,
    description text not null ,
    department_id bigint references department(id) on delete cascade on update cascade
);

create table if not exists employee (
    id bigint generated by default as identity unique not null ,
    name varchar not null ,
    surname varchar not null ,
    patronymic varchar not null ,
    about text not null ,
    passport varchar not null unique ,
    identity_id bigint references identity(id) on delete set null on update cascade ,
    address_id bigint references address(id) on delete set null on update cascade ,
    position_id bigint references position(id) on DELETE set null on update cascade ,
    filial_department_id bigint references filial_department(id) on delete set null on update cascade
);

create table if not exists plane (
    id bigint generated by default as identity unique not null ,
    number varchar not null ,
    model varchar not null unique ,
    business_class bigint not null ,
    economy_class bigint not null ,
    free boolean not null ,
    in_service boolean not null
);

create table if not exists cabin_type (
    id bigint generated by default as identity unique not null ,
    name varchar not null unique
);

create table if not exists flight (
    id bigint generated by default as identity unique not null ,
    number varchar not null unique ,
    departure_id bigint references airport(id) on delete set null on update cascade ,
    arrival_id bigint references airport(id) on delete set null on update cascade ,
    plane_id bigint references plane(id) on delete set null on update cascade ,
    departure_at timestamp not null check ( departure_at < arrival_at ) ,
    arrival_at timestamp not null check ( arrival_at > departure_at ) ,
    in_progress boolean not null ,
    completed boolean not null
);

create table if not exists flight_seat (
    id bigint generated by default as identity unique not null ,
    flight_id bigint references flight(id) on delete cascade on update cascade ,
    number bigint not null ,
    cabin_type_id bigint references cabin_type(id) on delete set null on update cascade ,
    purchased boolean not null ,
    closed boolean not null
);

create table flight_employee (
    flight_id bigint references flight(id) on delete cascade on update cascade ,
    employee_id bigint references employee(id) on delete cascade on update cascade
);

create table if not exists ticket (
    id bigint generated by default as identity unique not null ,
    flight_id bigint references flight(id) on delete set null on update cascade ,
    cabin_type_id bigint references cabin_type(id) on DELETE set null on update cascade ,
    price bigint not null ,
    amount bigint not null ,
    closed boolean not null
);

create table if not exists ordered_ticket (
    id bigint generated by default as identity unique not null ,
    identity_id bigint references identity(id) on delete set null on update cascade ,
    ticket_id bigint references ticket(id) on delete set null on update cascade ,
    flight_seat_id bigint references flight_seat(id) on delete set null on update cascade ,
    closed boolean not null
);