
### Authority Requests

###
GET /authorities
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
GET /authorities/by-id?authorityId=1
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
POST /authorities/create-update
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "name": "MODER"
}

###
POST /authorities/create-update
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "id": 4,
    "name": "MODERATOR"
}

###
DELETE /authorities/delete?authorityId=4
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

### Identity Requests

###
GET /identities
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
GET /identities/by-id?identityId=3
Host: localhost:9000
Authorization: Basic user@gmail.com user

###
GET /identities/by-username?username=admin
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
POST /identities/create
Host: localhost:9000
Content-Type: application/json

{
    "username": "burgvv",
    "password": "cg3audio",
    "email": "burgvv@gmail.com",
    "phone": "9139035373"
}

###
POST /identities/update?identityId=4
Host: localhost:9000
Authorization: Basic burgvv@gmail.com cg3audio
Content-Type: application/json

{
    "username": "burgasvv",
    "email": "burgasvv@mail.ru"
}

###
POST /identities/change-password?identityId=4
Host: localhost:9000
Authorization: Basic burgasvv@mail.ru cg3audio

###
PUT /identities/set-password?identityId=4&token=439af913-37d0-4235-a197-da074da6d92a&password=showconnerycg3audio
Host: localhost:9000
Authorization: Basic burgasvv@mail.ru cg3audio

###
PUT /identities/enable-disable?identityId=4&enabled=false
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

### Address Requests

###
POST /addresses/create-update-secured
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "cityId": 1,
    "street": "Калужская",
    "house": "12a",
    "apartment": "56"
}

###
POST /addresses/create-update-secured
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "id": 1,
    "cityId": 1,
    "street": "Московская",
    "house": "78/1",
    "apartment": "45"
}

### Airport Requests

###
POST /airports/create-update
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "name": "Домодедово",
    "address": {
        "cityId": 1,
        "street": "Московская",
        "house": "15/2"
    },
    "opened": true
}

###
POST /airports/create-update
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "id": 1,
    "name": "Шереметьево",
    "address": {
        "id": 1
    },
    "opened": true
}

### Filial Requests

###
POST /filials/create-update
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "name": "Филиал на Клюквенной",
    "address": {
        "cityId": 2,
        "street": "Клюквенная",
        "house": "78"
    },
    "opensAt": "08:00",
    "closesAt": "22:00",
    "opened": true
}

### Department Requests

###
GET /departments
Host: localhost:9000

###
GET /departments/by-id?departmentId=1
Host: localhost:9000

###
POST /departments/create-update
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "name": "New Department",
    "description": "New description for department"
}

###
POST /departments/create-update
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "id": 1,
    "name": "New Department EDITED",
    "description": "New description for department EDITED"
}

###
DELETE /departments/delete?departmentId=1
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

### Filial Department Requests

###
GET /filial-departments
Host: localhost:9000

###
GET /filial-departments/by-filial-department?filialId=1&departmentId=1
Host: localhost:9000

###
POST /filial-departments/create-update
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "filial": {
        "name": "Филиал на Мурманской",
        "address": {
            "cityId": 2,
            "street": "Мурманская",
            "house": "90"
        },
        "opensAt": "08:00",
        "closesAt": "22:00",
        "opened": true
    },
    "department": {
        "name": "New Department",
        "description": "New description for department"
    }
}

### Position Requests

###
POST /positions/create-update
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "name": "New Position",
    "description": "New position description",
    "departmentId": 1
}

###
POST /positions/create-update
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "id": 1,
    "name": "New Position EDITED",
    "description": "New position description EDITED"
}

###
DELETE /positions/delete?positionId=1
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

### Require Requests

###
POST /requires/create-update?userId=3
Host: localhost:9000
Authorization: Basic user@gmail.com user
Content-Type: application/json

{
    "name": "Victor",
    "surname": "Carov",
    "patronymic": "Sergeich",
    "passport": "8080 345678",
    "adminId": 1
}

### Require Answer Requests

###
GET /require-answers/by-user?userId=3
Host: localhost:9000
Authorization: Basic user@gmail.com user

###
GET /require-answers/by-admin?adminId=1
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
POST /require-answers/send-answer-or-token?adminId=1
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "allowed": false,
    "explanation": "Вам не разрешено стать сотрудником компании",
    "requireId": 1
}

### Employee Requests

###
GET /employees/by-id?employeeId=1
Host: localhost:9000
Authorization: Basic user@gmail.com user

###
POST /employees/create?token=a7aa617b-0a17-41f1-8bc0-4f778eb969a4
Host: localhost:9000
Authorization: Basic user@gmail.com user
Content-Type: application/json

{
    "about": "New description for employee",
    "address": {
        "cityId": 1,
        "street": "Novakova",
        "house": 36,
        "apartment": 12
    },
    "identityId": 3,
    "positionId": 1,
    "filialDepartmentId": 1
}

### Flight Requests

###
GET /flights
Host: localhost:9000

###
GET /flights/by-departure-city-by-arrival-city?departureCityId=1&arrivalCityId=2&departureDate=2025-10-25
Host: localhost:9000

###
GET /flights/by-departure-city-by-arrival-city?departureCityId=1&arrivalCityId=2
Host: localhost:9000

###
GET /flights/by-departure-city-by-arrival-city-back?flightId=1
Host: localhost:9000

###
GET /flights/by-id?flightId=1
Host: localhost:9000

###
POST /flights/create-update
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "departureId": 1,
    "arrivalId": 4,
    "planeId": 1,
    "businessPrice": 50000,
    "economyPrice": 25000,
    "departureAt": "2025-10-25T10:00",
    "arrivalAt": "2025-10-25T12:30",
    "inProgress": false,
    "completed": false
}

###
POST /flights/create-update
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "departureId": 4,
    "arrivalId": 1,
    "planeId": 3,
    "businessPrice": 60000,
    "economyPrice": 30000,
    "departureAt": "2025-11-25T13:00",
    "arrivalAt": "2025-11-25T15:30",
    "inProgress": false,
    "completed": false
}

###
POST /flights/add-employee?flightId=1&employeeId=1
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
DELETE /flights/remove-employee?flightId=1&employeeId=1
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
PUT /flights/start-flight?flightId=1
Host: localhost:9000
Authorization: Basic employee@gmail.com employee

###
PUT /flights/complete-flight?flightId=1
Host: localhost:9000
Authorization: Basic employee@gmail.com employee

### Ordered-Ticket Requests

###
GET /ordered-tickets/in-session
Host: localhost:9000

###
POST /ordered-tickets/order-ticket-identity?identityId=3
Host: localhost:9000
Authorization: Basic user@gmail.com user
Content-Type: application/json

{
    "ticketId": 1,
    "flightSeatId": 56
}

###
DELETE /ordered-tickets/cancel-ordered-ticket?orderedTicketId=1
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
POST /ordered-tickets/order-ticket-session
Host: localhost:9000
Authorization: Basic user@gmail.com user
Content-Type: application/json

{
    "ticketId": 1,
    "flightSeatId": 31
}