

create table if not exists image (
    id bigint generated by default as identity unique not null ,
    name varchar not null ,
    content_type varchar not null ,
    size bigint not null ,
    format varchar not null ,
    data bytea not null
);

create table if not exists authority (
    id bigint generated by default as identity unique not null,
    name varchar not null unique
);

create table if not exists identity (
    id bigint generated by default as identity unique not null ,
    username varchar not null unique ,
    password varchar not null ,
    email varchar not null unique ,
    phone varchar not null unique ,
    registered_at timestamp not null ,
    enabled boolean not null ,
    authority_id bigint references authority(id) on delete set null on update cascade ,
    image_id bigint references image(id) on delete set null on update cascade
);

create table if not exists country (
    id bigint generated by default as identity unique not null ,
    name varchar not null unique ,
    description text not null ,
    population bigint not null ,
    image_id bigint references image(id) on delete set null on update cascade
);

create table if not exists city (
    id bigint generated by default as identity unique not null ,
    name varchar not null unique ,
    description text not null ,
    population bigint not null ,
    country_id bigint references country(id) on delete set null on update cascade ,
    capital boolean not null ,
    image_id bigint references image(id) on delete set null on update cascade
);

create table if not exists language (
    id bigint generated by default as identity unique not null ,
    name varchar not null unique
);

create table if not exists sight (
    id bigint generated by default as identity unique not null ,
    name varchar not null unique ,
    description text not null ,
    city_id bigint references city(id) on delete set null on update cascade ,
    image_id bigint references image(id) on delete set null on update cascade
);

create table if not exists guide (
    id bigint generated by default as identity unique not null ,
    name varchar not null ,
    surname varchar not null ,
    patronymic varchar not null ,
    phone varchar not null ,
    about text not null ,
    image_id bigint references image(id) on delete set null on update cascade
);

create table if not exists guide_language (
    guide_id bigint references guide(id) on update cascade on delete cascade ,
    language_id bigint references language(id) on update cascade on delete cascade ,
    primary key (guide_id, language_id)
);

create table if not exists excursion (
    id bigint generated by default as identity unique not null ,
    name varchar not null ,
    description text not null ,
    guide_id bigint references guide(id) on delete set null on update cascade ,
    cost bigint not null ,
    starts timestamp not null check ( starts < ends ),
    ends timestamp not null check ( ends > starts ) ,
    in_progress boolean ,
    passed boolean ,
    image_id bigint references image(id) on update set null on delete cascade
);

create table if not exists excursion_sight (
    excursion_id bigint references excursion(id) on delete cascade on update cascade ,
    sight_id bigint references sight(id) on delete cascade on update cascade ,
    primary key (excursion_id, sight_id)
);

create table if not exists excursion_identity (
    excursion_id bigint references excursion(id) on delete cascade on update cascade ,
    identity_id bigint references identity(id) on delete cascade on update cascade ,
    primary key (excursion_id, identity_id)
);

create table if not exists payment (
    id bigint generated by default as identity unique not null ,
    identity_id bigint references identity(id) on delete set null on update cascade ,
    excursion_id bigint references excursion(id) on delete set null on update cascade ,
    payed_at timestamp not null
);