
services:

  postgres:
    image: postgres:latest
    container_name: hotel_backend_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotel_backend
      PGDATA: /var/lib/data/postgresql

  hotel-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9020:9020"
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hotel_backend