


### Authentication Requests



###
GET /authentication/csrf-token
Host: localhost:9020



### Authority Requests



###
GET /authorities
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /authorities/async
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /authorities/by-id?authorityId=1
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /authorities/by-id/async?authorityId=2
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
POST /authorities/create-update
Host: localhost:9020
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "name": "MODER"
}

###
POST /authorities/create-update/async
Host: localhost:9020
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "id": 4,
    "name": "MODERATOR"
}

###
DELETE /authorities/delete?authorityId=4
Host: localhost:9020
Authorization: Basic admin@gmail.com admin



### Identity Requests



###
GET /identities
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /identities/async
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /identities/pages/1?size=2
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /identities/by-id?identityId=1
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /identities/by-id/async?identityId=3
Host: localhost:9020
Authorization: Basic client@gmail.com client

###
POST /identities/create
Host: localhost:9020
Content-Type: application/json

{
    "username": "burgvv",
    "password": "cg3audio",
    "email": "burgvv@gmail.com",
    "phone": "9139035678",
    "authorityId": 3
}

###
POST /identities/update?identityId=4
Host: localhost:9020
Authorization: Basic burgvv@gmail.com cg3audio
Content-Type: application/json

{
    "username": "burgasvv",
    "email": "burgasvv@gmail.com",
    "phone": "9139038923"
}

###
PUT /identities/activate-deactivate?identityId=3&enable=true
Host: localhost:9020
Authorization: Basic admin@gmail.com admin



### Country Requests



###
GET /countries
Host: localhost:9020

###
GET /countries/pages/1?size=5
Host: localhost:9020

###
GET /countries/async
Host: localhost:9020

###
GET /countries/by-id?countryId=1
Host: localhost:9020

###
GET /countries/by-id/async?countryId=2
Host: localhost:9020

###
POST /countries/create-update
Host: localhost:9020
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "name": "Испания",
    "description": "Описание страны Испания"
}

###
POST /countries/create-update/async
Host: localhost:9020
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "id": 4,
    "name": "Испания EDITED"
}

###
DELETE /countries/delete?countryId=4
Host: localhost:9020
Authorization: Basic admin@gmail.com admin



### City Requests



###
GET /cities
Host: localhost:9020

###
GET /cities/async
Host: localhost:9020

###
GET /cities/pages/1?size=3
Host: localhost:9020

###
GET /cities/by-id?cityId=1
Host: localhost:9020

###
GET /cities/by-id/async?cityId=2
Host: localhost:9020

###
GET /cities/by-name?name=Шанхай
Host: localhost:9020

###
GET /cities/by-name/async?name=Пекин
Host: localhost:9020

###
POST /cities/create-update
Host: localhost:9020
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "name": "Волгоград",
    "description": "Описание города Волгоград",
    "countryId": 1,
    "capital": false
}

###
POST /cities/create-update/async
Host: localhost:9020
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "id": 7,
    "description": "Описание города Волгоград EDITED"
}

###
DELETE /cities/delete?cityId=7
Host: localhost:9020
Authorization: Basic admin@gmail.com admin



### Hotel Requests



###
GET /hotels
Host: localhost:9020

###
GET /hotels/async
Host: localhost:9020

###
GET /hotels/pages/1?size=5
Host: localhost:9020

###
GET /hotels/by-id?hotelId=1
Host: localhost:9020

###
GET /hotels/by-id/async?hotelId=2
Host: localhost:9020

###
GET /hotels/by-name?name=Marriot
Host: localhost:9020

###
GET /hotels/by-name/async?name=Long River
Host: localhost:9020



### Filial Requests



###
GET /filials
Host: localhost:9020

###
GET /filials/async
Host: localhost:9020

###
GET /filials/pages/1?size=3
Host: localhost:9020

###
GET /filials/by-id?filialId=1
Host: localhost:9020

###
GET /filials/by-id/async?filialId=2
Host: localhost:9020

###
POST /filials/create-update
Host: localhost:9020
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "hotelId": 3,
    "address": {
        "cityId": 1,
        "street": "Сокольники",
        "house": "34/1"
    },
    "luxRooms": 15,
    "economyRooms": 150,
    "departmentIds": [1, 2, 3, 4, 5, 6, 11]
}

###
POST /filials/create-update/async
Host: localhost:9020
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "id": 6,
    "luxRooms": 20,
    "economyRooms": 200
}



### Department Requests



###
GET /departments
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /departments/async
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /departments/pages/1?size=5
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /departments/by-filial?filialId=1
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /departments/by-filial/async?filialId=3
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /departments/by-id?departmentId=1
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /departments/by-id/async?departmentId=3
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
POST /departments/create-update
Host: localhost:9020
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "name": "New Department",
    "description": "New description for the new department"
}

###
POST /departments/create-update/async
Host: localhost:9020
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "id": 12,
    "name": "New Department EDITED"
}

###
DELETE /departments/delete?departmentId=12
Host: localhost:9020
Authorization: Basic admin@gmail.com admin



### Position Requests



###
GET /positions
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /positions/async
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /positions/pages/1?size=6
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /positions/by-id?positionId=1
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /positions/by-id/async?positionId=2
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
POST /positions/create-update
Host: localhost:9020
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "name": "New position",
    "description": "Description for new Position",
    "departmentId": 1
}

###
POST /positions/create-update
Host: localhost:9020
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "id": 19,
    "name": "New Position EDITED"
}

###
DELETE /positions/delete?positionId=19
Host: localhost:9020
Authorization: Basic admin@gmail.com admin



### Employee Requests



###
GET /employees
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /employees/async
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /employees/by-id?employeeId=1
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /employees/by-id/async?employeeId=2
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
POST /employees/create-update
Host: localhost:9020
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "name": "Василий",
    "surname": "Киреев",
    "patronymic": "Кириллович",
    "about": "Информация о Василии",
    "passport": "5793 958375",
    "filialId": 1,
    "positionId": 2
}

###
DELETE /employees/delete?employeeId=3
Host: localhost:9020
Authorization: Basic admin@gmail.com admin



### Room Requests



###
GET /rooms/by-filial?filialId=1
Host: localhost:9020

###
GET /rooms/by-filial/async?filialId=2
Host: localhost:9020

###
GET /rooms/by-id?roomId=1
Host: localhost:9020

###
GET /rooms/by-id/async?roomId=2
Host: localhost:9020

###
POST /rooms/create-update
Host: localhost:9020
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "number": 102,
    "roomTypeId": 1,
    "filialId": 1,
    "description": "New room description",
    "hourPrice": 2500
}



### Client Requests



###
GET /clients
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /clients/async
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
POST /clients/create-update
Host: localhost:9020
X-Csrf-Token: JvaR828vvpNiA5gb2GGuSsjDR_ebRfMhiV01iCDA8lHc_F7jEcWmwV0e2KNPNfop6kyaL6ygapX-d8oMvjlUu0H1x2nuzjuB
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "name": "Olga",
    "surname": "Parusheva",
    "patronymic": "Igorevna",
    "passport": "8954839385"
}

###
POST /clients/create-update
Host: localhost:9020
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "name": "Aleksandr",
    "surname": "Kirsanov",
    "patronymic": "Valer'evich",
    "passport": "7652786354"
}

###
POST /rooms/rent-room
Host: localhost:9020
Content-Type: application/json

{
    "clientId": 1,
    "roomId": 3,
    "rentedFrom": "2025-05-19T15:00",
    "rentedTo": "2025-05-21T12:00"
}

###
POST /rooms/rent-room
Host: localhost:9020
Content-Type: application/json

{
    "clientId": 2,
    "roomId": 2,
    "rentedFrom": "2025-05-20T23:00",
    "rentedTo": "2025-05-22T15:00"
}



### Payment Requests



###
GET /payments/by-client?clientId=1
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
GET /payments/by-client/async?clientId=1
Host: localhost:9020
Authorization: Basic admin@gmail.com admin

###
PUT /payments/close-payment?clientId=1
Host: localhost:9020
Authorization: Basic admin@gmail.com admin