
server:
  port: 9000
spring:
  application:
    name: flight_backend
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/flight_backend
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        highlight_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect