
server:
  port: 9000
spring:
  application:
    name: ticket-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/ticket_service
    hikari:
      maximum-pool-size: 50
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        highlight_sql: true
    open-in-view: false