
server:
  port: 9000
spring:
  application:
    name: ticket-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ticket_service
    username: postgres
    password: postgres
    pool:
      initial-size: 25
      max-size: 50